name: Deploy to SSH Server

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Deploy Code
      #   run: |
      #     ssh -i ~/.ssh/id_rsa opc@158.101.21.48 "cd oracle-assistant && git pull origin main"
